### ISSUE TITLE
Document how to configure/use GitHub in the BD context

### ISSUE THREAD

**Issue by monkeypants** [monkeypants/bd-teamsport#1]
`docs/design.rst` has some implicit assumptions about how we will be using GitHub projects.

TODO: make them explicit (by describing them in `docs/`, with screenshots and words).

This will be done when:
 * a developer understands them well enough to automate them
 * a regular GitHub user can skim-read the docs quickly and understand perfectly
 * someone new to GitHub (e.g. peon) can follow them without confusion or difficulty

**Comment by monkeypants** [comment]
Note (per comment in #9) this might include manual tasks that become automated.

**Comment by monkeypants** [comment]
We need to:
 * [ ] describe and define the columns, and make a screen shot of that.
 * [ ] configure the github automatic stuff on the columns (new in backlog, closed to done, etc)
 * [ ] create a suite of SOPs describing actor workflows (gherkin will do?), not including peon stuff
 * [ ] document the peon SOPs separately, so that they are easy to factor out in #9
